### ISSUE TITLE
Rename Repo to align with all others

### ISSUE THREAD

**Issue by bretterer** [okta/okta-ios-jwt#18]
To align this repo with all the other verifiers, we should update our naming convention of this repo is possible to `okta-jwt-verifier-ios`

**Comment by jmelberg-okta** [comment]
Since this library is intended to perform JWT verification and signing, we made the decision to follow a different naming convention that closely mirrors repositories owned by our mobile teams.

**Comment by bdemers** [comment]
I agree with @bretterer, I think this should follow our convention

**Comment by bdemers** [comment]
i think the node one should be renamed too ;)

**Comment by jmelberg-okta** [comment]
As mentioned in my prior comment, we made the decision to use a different naming convention due to the specifics of this library. Separating this into two different libraries (**validation** and **signing**) was discussed during initial planning, however was nixed to ensure a single import for integrating into our existing products.

Closing this issue down, as we're going to keep the current name.
